### ISSUE TITLE
uncompyle6 2.9.2 can throw an AttributeError when calling `scanners.scanner2.opsize`

### ISSUE THREAD

**Issue by alexwlchan** [rocky/python-uncompyle6#62]
This was originally spotted in https://github.com/HypothesisWorks/hypothesis-python/issues/379, although it probably affects other users of this library.

---

uncompyle2.9.0 bumped the required version of xdis, specifically `xdis >= 3.2.0, < 3.3.0`. This coincides with a new release of xdis – previously it used 3.1.x.

In 2.9.0, [there’s a function `op_size`](https://github.com/rocky/python-uncompyle6/blob/59b597ea5dffb5795c48827196cac1e32e4ae608/uncompyle6/scanners/scanner2.py#L289) which refers to `self.opc.hasArgumentExtended`:

```python
def op_size(self, op):
    if op < self.opc.HAVE_ARGUMENT and op not in self.opc.hasArgumentExtended:
        return 1
    else:
        return 3
```

This name does not appear anywhere else in the uncompyle2 source tree. It did appear in xdis&nbsp;3.1.0, but was removed in xdis&nbsp;3.2.0, under https://github.com/rocky/python-xdis/commit/6046fa24663d4bc4b78e71b392daa26211f33b6a.

As a result, if you call this function with uncompyle2&nbsp;2.9.0 and xdis&nbsp;3.2.0, you throw an AttributeError in the second half of the `if` condition. We end up calling this function as part of Hypothesis, and this causes test runs to crash. We can work around this by pinning the versions, but this will affect other users of the library.

Given the rationale for removing this opcode in https://github.com/rocky/python-xdis/commit/6046fa24663d4bc4b78e71b392daa26211f33b6a was “It’s not used”, it seems like the solution is probably just to revert that commit and release a new minor version of xdis with the opcode restored.

**Comment by rocky** [comment]
I'd like to go forward, not backwards if possible. How about if I _remove_ uncompyle6 version 2.9.0 instead?

**Comment by alexwlchan** [comment]
Do you mean removing hasArgumentExtended from uncompyle6? I expect that would work – I’m pretty sure there’s nothing that low level in Hypothesis.

**Comment by rocky** [comment]
Between  uncompyle6 2.9.2 and 2.93  hasArgumentExtended  was removed
[unc-2.9.2-2.9.3.txt](https://github.com/rocky/python-uncompyle6/files/560503/unc-2.9.2-2.9.3.txt)

So possibly removing both uncompyle6 2.9.0 and uncompyle6 2.9.2 will do the trick. 

The reality is that each release right now of uncompyle6 is fixing bugs and covering more of the Python langauge. (For example, I'm working on handling Python 3 function annotations). 

So from my standpoint for now as soon as a new release is done, upgrades are useful since they reduce bugginess in decompiling.

**Comment by alexwlchan** [comment]
Ah, sorry, I got confused.

I’d missed that uncompyle6 2.9.3 had been released – literally just as we started seeing this issue. (This would also explain why I was stubbornly unable to repro the bug in a clean virtualenv!)

So it sounds like we don’t need any changes to uncompyle6, we just need to upgrade the version used with Hypothesis. I’ll do another run in our CI to double-check that fixes the problem.

**Comment by rocky** [comment]
Well, I'm sorry I haven't been tagging things properly. I think I have the release tagging fixed now.

If this works, I still probably would like to _remove_ 2.9.0, 2.9.1, and 2.9.2 from PyPI as there is a possibility for breakage when using with xdis 3.2.0 (in addition to the bug fixes in each version). 

Sorry for the breakage and the extra work and hassle it has caused you and the hypothesis users. Again, with luck by using semantic versioning better we won't have this problem in the future. 

I make lots of mistakes. That's why I work on [debuggers](https://pypi.python.org/pypi/trepan3k)

**Comment by alexwlchan** [comment]
No worries, I’m just glad to have the issue sorted. We’re still seeing a few issues with 2.9.3 in Hypothesis CI, but not the one with `hasArgumentExtended`. I’ll dig into those failures and let you know if they’re caused by something in uncompyle6.

Thanks for your help!
